### ISSUE TITLE
error on uploading settings file

### ISSUE THREAD

**Issue by hsitz** [nettoyeurny/re_configure#1]
I've just started playing around with re_configure, looks like a nice piece of work.

Using Python 3.9.9.

Haven't done much yet, but getting data out of re.corder is working.  I exported the settings to a file and made a couple tiny changes, then tried to --send the file back to the re.corder.

I got the error below.  Not sure how to proceed.

================

hsitz@Herberts-Air python % python3 re_configure.py -s ./config.json 
Setting user mode.
Traceback (most recent call last):
  File "/Users/herbertsitz/gitdir/re_configure/python/re_configure.py", line 201, in <module>
    conf = update_settings(r, updated_config(json_conf, cli_conf), chart)
  File "/Users/herbertsitz/gitdir/re_configure/python/re_configure.py", line 104, in update_settings
    r.set_user_mode(conf[USER_MODE])
  File "/Users/herbertsitz/gitdir/re_configure/python/re_corder.py", line 216, in set_user_mode
    self._run([0x21], [0x05, m])
  File "/Users/herbertsitz/gitdir/re_configure/python/re_corder.py", line 153, in _run
    raise FailedRequestException('Try holding Record, perhaps?', payload)
re_corder.FailedRequestException: Try holding Record, perhaps?

==============

Just tried to do something else, change user mode, and got identical error:

herbertsitz@Herberts-Air python % python3 re_configure.py -u Keyboard

**Comment by nettoyeurny** [comment]
The error message suggests that re_configure was able to talk to the re.corder but received an error response. Were you holding the Record button on the re.corder while running the script? Some settings, including user mode, require that you hold Record when changing them.

**Comment by hsitz** [comment]
That was it!  Sorry to trouble you for user error.  I'd been messing mostly
with midi and fingering settings, forgot (or never knew) that you had to
press the circle button.

BTW, I'm finally getting things dialed in on the re.corder and like it
quite a lot.  But I have a problem with condensation building up quite
quickly that makes it have problems recognizing whether keys are covered or
not.  It seems hard to get the condensation out, takes a long time.  I'm
curious whether you've had any issues with this?

I do plan to make use of your excellent work.  I prefer to have an
iPad/iPhone as my synth device, so I'm going to see if I can use your Sysex
message info to get Re_configure functions working with the Mozaic midi
scripting app.

Thanks!

-- Herb

**Comment by hsitz** [comment]
I just got the error again, user error again.  But this time the 'Try
holding Record, perhaps' made sense.  Before I thought it was something
about transaction processing going on, putting a "hold" on a database
record.  If that error message had just appeared as only text on StdOut I
would have understood it, having it happen in the Python trace made me
think the programmer was writing an interesting suggestion for . . .
himself.  Ha.  Thanks again.

**Comment by hsitz** [comment]
Oh, and one more thing, another reason I didn't understand that message was
I know that button only as "the circle button", never knew it was actually
meant to be analogous to a 'Record'.

**Comment by nettoyeurny** [comment]
You're very welcome --- glad to hear that things are working for you now.

I just pushed a revision that makes the error message a bit clearer :)

I do notice some condensation on occasion, but so far it never interfered with the sensors.

Mozaic scripts for iThings would be useful for a lot of people --- please keep me posted on your progress!
